services:
  nginx:
    image: sheriffexcel/nginx-demo
    build: .
    ports:
      - "80"
    depends_on:
      - postgres
    networks:
      - coolify

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coolify
    ports:
      - "5432"

networks:
  coolify:
    external: true

volumes:
  postgres_data:
